/home/yec23006/.local/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/yec23006/.local/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Epoch [1/200], Loss: 1447.9273
Epoch [2/200], Loss: 480.1754
Traceback (most recent call last):
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/PIL/ImageFile.py", line 515, in _save
    fh = fp.fileno()
         ^^^^^^^^^
AttributeError: '_idat' object has no attribute 'fileno'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/yec23006/projects/research/merfish/FasterRCNN/SSD.py", line 290, in <module>
    train_ssd(model, train_loader, num_epochs=num_epochs, learning_rate=learning_rate, device=device)
  File "/home/yec23006/projects/research/merfish/FasterRCNN/SSD.py", line 241, in train_ssd
    pred_images.append(wandb.Image(pred_img))
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 336, in _initialize_from_data
    self._image.save(tmp_path, transparency=None)
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/PIL/PngImagePlugin.py", line 1398, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/PIL/ImageFile.py", line 519, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/home/yec23006/.conda/envs/torch121/lib/python3.11/site-packages/PIL/ImageFile.py", line 538, in _encode_tile
    errcode, data = encoder.encode(bufsize)[1:]
                    ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt